### ISSUE TITLE
Definition of satisfiability for FOL

### ISSUE THREAD

**Issue by AmSpidey** [lclem/logic_course_2020-2021#5]
Problem book could use a definition of satisfiability for first order logic, since there is none. There are some mentions in Hilbert's proof system exercises, but it would be useful to put some definition much earlier, since there are exercises involving satisfiability since the start of the topic of FOL. :)

**Comment by lclem** [comment]
true that, it was somehow left implicit, but in fact it is good to make it explicit since different books treat free variables in different ways when dealing with satisfiability (i.e., depending on whether they should be interpreted existentially or universally; there are tradeoffs here); we will add an official definition in the following iteration, thanks!
